---
- name: Gather facts, if not present
  ansible.builtin.setup:
  when: not ansible_facts
  tags:
    - always

- name: Remove conflicting Docker packages
  ansible.builtin.package:
    name: "{{ conflicting_docker_packages }}"
    state: absent
  tags: install

- name: Install required packages for Docker
  ansible.builtin.package:
    name: '{{ required_pkgs }}'
    state: present
  tags: install


- name: Ensure /etc/apt/keyrings exists
  ansible.builtin.file:
    path: '{{gpg_key_path}}'
    state: directory
    mode: '{{gpg_key_mode}}'
  tags: install

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: '{{ gpg_key_uri }}'
    dest: '{{ gpg_key_path }}/docker.asc'
    mode: '{{ docker_gpg_key_mode }}'
    owner: root
    group: root
  tags: install

- name: Make Docker GPG key readable by all
  ansible.builtin.file:
    path: '{{gpg_key_path}}/docker.asc'
    mode: '{{docker_gpg_key_mode}}'
  tags: install


- name: Add Docker Apt Sources list file
  ansible.builtin.template:
    src: etc/apt/sources.list.d/docker.sources.j2
    dest: '{{ docker_apt_source_file_path }}'
    mode: '0644'
    owner: root
    group: root
  tags: install
    

- name: Update APT cache (only if older than apt_cache_valid_time variable)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: '{{apt_cache_valid_time}}'
  tags: 
    - install
    - update_pkg_cache_docker


- name: install docker 
  ansible.builtin.apt:
    name: '{{ docker_pkgs }}'
    state: '{{docker_pkg_state }}'
  tags: install
  notify:
    - Restart Docker